import 'package:flutter/material.dart';

/// Central Material Icon name → [IconData] resolver used by every factory
/// that accepts a string icon name (spec §2.5 `icon.icon`, navigation items,
/// timeline/tree/button leading, etc.).
///
/// Naming is always snake_case, matching the names on
/// https://fonts.google.com/icons and Flutter's `Icons` class. Unknown names
/// fall back to `Icons.help_outline` so authors get an obvious "missing
/// icon" cue rather than a generic black dot.
IconData resolveIconData(String name) {
  // Tolerate the `material:` informational prefix that authoring tools
  // (vibe asset picker, LLM patches) sometimes emit. Spec form is the
  // bare name; this keeps round-tripped values rendering correctly.
  final raw = name.startsWith('material:')
      ? name.substring('material:'.length)
      : name;
  final data = _map[raw] ?? _map[raw.toLowerCase()];
  if (data != null) return data;
  return Icons.help_outline;
}

// The map is intentionally flat (no computed keys) so a name can be resolved
// in O(1) without instantiating Flutter's entire Icons class tree.
const Map<String, IconData> _map = {
  // Navigation
  'home': Icons.home,
  'home_outlined': Icons.home_outlined,
  'menu': Icons.menu,
  'menu_open': Icons.menu_open,
  'close': Icons.close,
  'arrow_back': Icons.arrow_back,
  'arrow_forward': Icons.arrow_forward,
  'arrow_upward': Icons.arrow_upward,
  'arrow_downward': Icons.arrow_downward,
  'arrow_left': Icons.arrow_left,
  'arrow_right': Icons.arrow_right,
  'arrow_drop_down': Icons.arrow_drop_down,
  'arrow_drop_up': Icons.arrow_drop_up,
  'chevron_left': Icons.chevron_left,
  'chevron_right': Icons.chevron_right,
  'expand_less': Icons.expand_less,
  'expand_more': Icons.expand_more,
  'more_vert': Icons.more_vert,
  'more_horiz': Icons.more_horiz,
  'apps': Icons.apps,
  'dashboard': Icons.dashboard,
  'dashboard_outlined': Icons.dashboard_outlined,

  // Actions
  'add': Icons.add,
  'add_circle': Icons.add_circle,
  'add_circle_outline': Icons.add_circle_outline,
  'remove': Icons.remove,
  'remove_circle': Icons.remove_circle,
  'remove_circle_outline': Icons.remove_circle_outline,
  'check': Icons.check,
  'check_circle': Icons.check_circle,
  'check_circle_outline': Icons.check_circle_outline,
  'check_box': Icons.check_box,
  'check_box_outline_blank': Icons.check_box_outline_blank,
  'clear': Icons.clear,
  'cancel': Icons.cancel,
  'done': Icons.done,
  'done_all': Icons.done_all,
  'delete': Icons.delete,
  'delete_outline': Icons.delete_outline,
  'delete_forever': Icons.delete_forever,
  'edit': Icons.edit,
  'edit_outlined': Icons.edit_outlined,
  'save': Icons.save,
  'save_alt': Icons.save_alt,
  'send': Icons.send,
  'share': Icons.share,
  'copy': Icons.copy,
  'content_copy': Icons.content_copy,
  'content_cut': Icons.content_cut,
  'content_paste': Icons.content_paste,
  'refresh': Icons.refresh,
  'sync': Icons.sync,
  'undo': Icons.undo,
  'redo': Icons.redo,

  // Communication & Info
  'email': Icons.email,
  'email_outlined': Icons.email_outlined,
  'mail': Icons.mail,
  'mail_outline': Icons.mail_outline,
  'message': Icons.message,
  'chat': Icons.chat,
  'chat_bubble': Icons.chat_bubble,
  'chat_bubble_outline': Icons.chat_bubble_outline,
  'phone': Icons.phone,
  'call': Icons.call,
  'notifications': Icons.notifications,
  'notifications_outlined': Icons.notifications_outlined,
  'notifications_active': Icons.notifications_active,
  'notifications_off': Icons.notifications_off,
  'info': Icons.info,
  'info_outline': Icons.info_outline,
  'help': Icons.help,
  'help_outline': Icons.help_outline,
  'warning': Icons.warning,
  'warning_amber': Icons.warning_amber,
  'error': Icons.error,
  'error_outline': Icons.error_outline,
  'report': Icons.report,
  'bug_report': Icons.bug_report,

  // Common
  'search': Icons.search,
  'settings': Icons.settings,
  'settings_outlined': Icons.settings_outlined,
  'tune': Icons.tune,
  'filter_list': Icons.filter_list,
  'filter_alt': Icons.filter_alt,
  'sort': Icons.sort,
  'favorite': Icons.favorite,
  'favorite_border': Icons.favorite_border,
  'star': Icons.star,
  'star_border': Icons.star_border,
  'star_half': Icons.star_half,
  'bookmark': Icons.bookmark,
  'bookmark_border': Icons.bookmark_border,
  'thumb_up': Icons.thumb_up,
  'thumb_down': Icons.thumb_down,
  'visibility': Icons.visibility,
  'visibility_off': Icons.visibility_off,
  'lock': Icons.lock,
  'lock_open': Icons.lock_open,
  'lock_outline': Icons.lock_outline,
  'key': Icons.key,

  // File / Folder
  'folder': Icons.folder,
  'folder_open': Icons.folder_open,
  'folder_outlined': Icons.folder_outlined,
  'folder_special': Icons.folder_special,
  'insert_drive_file': Icons.insert_drive_file,
  'description': Icons.description,
  'article': Icons.article,
  'attach_file': Icons.attach_file,
  'attachment': Icons.attachment,
  'download': Icons.download,
  'upload': Icons.upload,
  'file_download': Icons.file_download,
  'file_upload': Icons.file_upload,
  'cloud': Icons.cloud,
  'cloud_download': Icons.cloud_download,
  'cloud_upload': Icons.cloud_upload,
  'cloud_off': Icons.cloud_off,
  'cloud_done': Icons.cloud_done,

  // People
  'person': Icons.person,
  'person_outline': Icons.person_outline,
  'person_add': Icons.person_add,
  'people': Icons.people,
  'group': Icons.group,
  'group_add': Icons.group_add,
  'account_circle': Icons.account_circle,
  'account_box': Icons.account_box,
  'face': Icons.face,
  'supervisor_account': Icons.supervisor_account,

  // Location & Map
  'location_on': Icons.location_on,
  'location_off': Icons.location_off,
  'location_city': Icons.location_city,
  'map': Icons.map,
  'place': Icons.place,
  'pin_drop': Icons.pin_drop,
  'location_pin': Icons.location_pin,
  'my_location': Icons.my_location,
  'gps_fixed': Icons.gps_fixed,
  'navigation': Icons.navigation,
  'directions': Icons.directions,
  'near_me': Icons.near_me,

  // Time / Date
  'access_time': Icons.access_time,
  'timer': Icons.timer,
  'today': Icons.today,
  'event': Icons.event,
  'event_available': Icons.event_available,
  'event_note': Icons.event_note,
  'date_range': Icons.date_range,
  'calendar_today': Icons.calendar_today,
  'calendar_month': Icons.calendar_month,
  'schedule': Icons.schedule,
  'alarm': Icons.alarm,
  'history': Icons.history,

  // Device
  'computer': Icons.computer,
  'laptop': Icons.laptop,
  'smartphone': Icons.smartphone,
  'tablet': Icons.tablet,
  'watch': Icons.watch,
  'tv': Icons.tv,
  'devices': Icons.devices,
  'keyboard': Icons.keyboard,
  'mouse': Icons.mouse,
  'print': Icons.print,
  'power': Icons.power,
  'wifi': Icons.wifi,
  'bluetooth': Icons.bluetooth,
  'battery_full': Icons.battery_full,

  // Shopping
  'shopping_cart': Icons.shopping_cart,
  'shopping_bag': Icons.shopping_bag,
  'store': Icons.store,
  'storefront': Icons.storefront,
  'payment': Icons.payment,
  'credit_card': Icons.credit_card,
  'local_offer': Icons.local_offer,
  'local_mall': Icons.local_mall,
  'receipt': Icons.receipt,
  'attach_money': Icons.attach_money,

  // Media
  'play_arrow': Icons.play_arrow,
  'play_circle': Icons.play_circle,
  'play_circle_outline': Icons.play_circle_outline,
  'pause': Icons.pause,
  'pause_circle': Icons.pause_circle,
  'stop': Icons.stop,
  'skip_next': Icons.skip_next,
  'skip_previous': Icons.skip_previous,
  'fast_forward': Icons.fast_forward,
  'fast_rewind': Icons.fast_rewind,
  'volume_up': Icons.volume_up,
  'volume_down': Icons.volume_down,
  'volume_off': Icons.volume_off,
  'volume_mute': Icons.volume_mute,
  'music_note': Icons.music_note,
  'movie': Icons.movie,
  'videocam': Icons.videocam,
  'photo': Icons.photo,
  'photo_camera': Icons.photo_camera,
  'image': Icons.image,
  'camera': Icons.camera,
  'camera_alt': Icons.camera_alt,
  'mic': Icons.mic,
  'mic_off': Icons.mic_off,
  'headset': Icons.headset,

  // Charts / Data
  'trending_up': Icons.trending_up,
  'trending_down': Icons.trending_down,
  'trending_flat': Icons.trending_flat,
  'show_chart': Icons.show_chart,
  'bar_chart': Icons.bar_chart,
  'pie_chart': Icons.pie_chart,
  'bubble_chart': Icons.bubble_chart,
  'insights': Icons.insights,
  'analytics': Icons.analytics,
  'table_chart': Icons.table_chart,
  'view_list': Icons.view_list,
  'view_module': Icons.view_module,
  'grid_view': Icons.grid_view,

  // Formatting / Editor
  'format_bold': Icons.format_bold,
  'format_italic': Icons.format_italic,
  'format_underline': Icons.format_underline,
  'format_list_bulleted': Icons.format_list_bulleted,
  'format_list_numbered': Icons.format_list_numbered,
  'code': Icons.code,
  'terminal': Icons.terminal,

  // Misc / Status
  'security': Icons.security,
  'verified': Icons.verified,
  'verified_user': Icons.verified_user,
  'gavel': Icons.gavel,
  'shield': Icons.shield,
  'language': Icons.language,
  'public': Icons.public,
  'translate': Icons.translate,
  'palette': Icons.palette,
  'color_lens': Icons.color_lens,
  'brush': Icons.brush,
  'build': Icons.build,
  'extension': Icons.extension,
  'widgets': Icons.widgets,
  'inventory': Icons.inventory,
  'inventory_2': Icons.inventory_2,
  'flag': Icons.flag,
  'label': Icons.label,
  'lightbulb': Icons.lightbulb,
  'lightbulb_outline': Icons.lightbulb_outline,
  'dark_mode': Icons.dark_mode,
  'light_mode': Icons.light_mode,
  'circle': Icons.circle,
  'circle_outlined': Icons.circle_outlined,
  'square': Icons.square,
  'fiber_manual_record': Icons.fiber_manual_record,

  // Local shipping / transport
  'local_shipping': Icons.local_shipping,
  'directions_car': Icons.directions_car,
  'directions_bus': Icons.directions_bus,
  'directions_bike': Icons.directions_bike,
  'directions_walk': Icons.directions_walk,
  'flight': Icons.flight,

  // Additional common
  'assignment': Icons.assignment,
  'auto_awesome': Icons.auto_awesome,
  'calculate': Icons.calculate,
  'design_services': Icons.design_services,
  'gps_not_fixed': Icons.gps_not_fixed,
  'gps_off': Icons.gps_off,
  'hub': Icons.hub,
  'list': Icons.list,
  'location': Icons.location_on,
  'pan_tool': Icons.pan_tool,
  'phone_android': Icons.phone_android,
  'phone_iphone': Icons.phone_iphone,
  'profile': Icons.person,
  'sensors': Icons.sensors,
  'speed': Icons.speed,
  'swap_horiz': Icons.swap_horiz,
  'swap_vert': Icons.swap_vert,
  'temperature': Icons.thermostat,
  'text_fields': Icons.text_fields,
  'thermostat': Icons.thermostat,
  'touch_app': Icons.touch_app,
  'link': Icons.link,
  'open_in_new': Icons.open_in_new,
  'launch': Icons.launch,
  'zoom_in': Icons.zoom_in,
  'zoom_out': Icons.zoom_out,
  'fullscreen': Icons.fullscreen,
  'fullscreen_exit': Icons.fullscreen_exit,
  'logout': Icons.logout,
  'login': Icons.login,
  'exit_to_app': Icons.exit_to_app,
  'power_settings_new': Icons.power_settings_new,
};
